// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivsannscvapebbtdjjrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2c2FubnNjdmFwZWJidGRqanJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTg0NTgsImV4cCI6MjA2MzI5NDQ1OH0.7E2SRFj2TGYLLSm7kYkWEe62yPzvR7ILWDTy7fJfgx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);